export const data = [
  {
    id: "01", //numbers starting with zero are not permissable in strict mode so changed them in string to use
    name: "Pratham Singh",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=JW&height=36&width=36",
    projects: ["ABC"],
    hours: "8 hrs",
    role: "Full-time",
    actions: "icon",
  },
  {
    id: "02",
    name: "Pragati Mishra",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=AH&height=36&width=36",
    projects: ["ABC-4th"],
    hours: "4 hrs",
    role: "Intern",
    actions: "icon",
  },
  {
    id: "03",
    name: "Satya Mall",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=SW&height=36&width=36",
    projects: ["ABC"],
    hours: "3 hrs",
    role: "Full-time",
    actions: "icon",
  },
  {
    id: "04",
    name: "Aditi Singh",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=JM&height=36&width=36",
    projects: ["ABC"],
    hours: "5 hrs",
    role: "Contractor",
    actions: "icon",
  },
  {
    id: "05",
    name: "Ankit Rao",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=MD&height=36&width=36",
    projects: ["XYZ-6h", "TCS-4"],
    hours: "10 hrs",
    role: "Intern",
    actions: "icon",
  },
  {
    id: "06",
    name: "Akriti Rao",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=DP&height=36&width=36",
    projects: ["ABC"],
    hours: "5 hrs",
    role: "Full-time",
    actions: "icon",
  },
  {
    id: "07",
    name: "Edda Maviya",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=CC&height=36&width=36",
    projects: ["ABC"],
    hours: "7 hrs",
    role: "Contractor",
    actions: "icon",
  },
  {
    id: "08",
    name: "Anuj Verma",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=EP&height=36&width=36",
    projects: ["XYZ-5h", "ABC-4h"],
    hours: "9 hrs",
    role: "Intern",
    actions: "icon",
  },
  {
    id: "09",
    name: "Priya Singh",
    email: "abc@domain.com",
    imageUrl: "https://hub.dummyapis.com/Image?text=ED&height=36&width=36",
    projects: ["ABC"],
    hours: "7 hrs",
    role: "Contractor",
    actions: "icon",
  },
];
